
-- xÓA DỮ LIỆU
DELETE [dbo].[DONGIA_CPTT]
DELETE [dbo].[CHIPHI_THANHTOAN]
DELETE [dbo].[CUDAN-CANHO]
DELETE [dbo].[NHANVIEN_TOANHA]
DELETE [dbo].[CUDAN]
DELETE [dbo].[CANHO]
DELETE [dbo].[LOAICANHO] 
DELETE [dbo].[TANGLAU] 
DELETE [dbo].[TOANHA]


DELETE [dbo].[CHITIETHOADON_DVCC]
DELETE [dbo].[HOADON_DVDK]
DELETE [dbo].[HOADON_DVCC]
DELETE [dbo].[GIA_DVDK]
DELETE [dbo].[GIA_DVCC]
DELETE [dbo].[DICHVU_DINHKY]
DELETE [dbo].[DICHVU_CONGCONG]
-- XÓA BẢNG

-- XÓA VIEW 
DROP VIEW VIEW_APARTMENT
DROP VIEW VIEW_BLOCK
DROP VIEW VIEW_FLOOR
DROP VIEW VIEW_NHANKHAU
DROP VIEW VIEW_SERVICE


-- XÓA STORED
DROP PROC PR_GetCustomApartment



------ DỊCH VỤ
DROP TABLE [dbo].[CHITIETHOADON_DVDK]
DROP TABLE [dbo].[CHITIETHOADON_DVCC]
DROP TABLE [dbo].[HOADON_DVDK]
DROP TABLE [dbo].[HOADON_DVCC]
DROP TABLE [dbo].[GIA_DVDK]
DROP TABLE [dbo].[GIA_DVCC]
DROP TABLE [dbo].[DICHVU_DINHKY]
DROP TABLE [dbo].[DICHVU_CONGCONG]