
-- Thêm View Nhan Khau
CREATE VIEW VIEW_NhanKhau AS 
SELECT        dbo.TOANHA.TENBLOCK, dbo.TANGLAU.TENTANGLAU, dbo.LOAICANHO.TENLOAI_CH, dbo.LOAICANHO.DIENTICH, dbo.LOAICANHO.SOPHONGNGU, dbo.LOAICANHO.SONGUOITOIDA, dbo.[CUDAN-CANHO].NGAYBATDAUO, 
                         dbo.[CUDAN-CANHO].NGAYHETO, dbo.CANHO.TENCANHO, dbo.CUDAN.TENCUDAN, dbo.CUDAN.NGAYSINH, dbo.CUDAN.SODIENTHOAI, dbo.CANHO.CHUHO, dbo.CANHO.SONGUOIO, dbo.CUDAN.GIOITINH, 
                         dbo.CUDAN.CHUNGMINHNHANDAN
FROM            dbo.CANHO INNER JOIN
                         dbo.[CUDAN-CANHO] ON dbo.CANHO.MACANHO = dbo.[CUDAN-CANHO].MACANHO INNER JOIN
                         dbo.CUDAN ON dbo.[CUDAN-CANHO].MACUDAN = dbo.CUDAN.MACUDAN INNER JOIN
                         dbo.LOAICANHO ON dbo.CANHO.MALOAI_CH = dbo.LOAICANHO.MALOAI_CH INNER JOIN
                         dbo.TANGLAU ON dbo.CANHO.MATANGLAU = dbo.TANGLAU.MATANGLAU INNER JOIN
                         dbo.TOANHA ON dbo.TANGLAU.MABLOCK = dbo.TOANHA.MABLOCK
GO