
/****** Object:  StoredProcedure [dbo].[PR_login]    Script Date: 26-Jun-20 4:43:55 PM ******/
-- proc Login
CREATE PROCEDURE [dbo].[PR_login] 
 @username varchar(30), @password varchar(30)
AS
BEGIN
	SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @username and MATKHAU = @password
END

GO
-- Tao View Nhan Khau
CREATE VIEW VIEW_NhanKhau AS 

WITH DSCuDan (	TENBLOCK,TENTANGLAU,TENLOAI_CH, DIENTICH, SOPHONGNGU, SONGUOITOIDA, NGAYBATDAUO,NGAYHETO, TENCANHO, TENCUDAN,NGAYSINH, SODIENTHOAI, CHUHO, SONGUOIO,GIOITINH,CMND_CUDAN)  
	AS  
	(  
		SELECT       dbo.[CUDAN-CANHO].ID, dbo.TOANHA.TENBLOCK, dbo.TANGLAU.TENTANGLAU, dbo.LOAICANHO.TENLOAI_CH, dbo.LOAICANHO.DIENTICH, dbo.LOAICANHO.SOPHONGNGU, dbo.LOAICANHO.SONGUOITOIDA, dbo.[CUDAN-CANHO].NGAYBATDAUO, 
								 dbo.[CUDAN-CANHO].NGAYHETO, dbo.CANHO.TENCANHO, dbo.CUDAN.TENCUDAN, dbo.CUDAN.NGAYSINH, dbo.CUDAN.SODIENTHOAI, dbo.CANHO.CHUHO, dbo.CANHO.SONGUOIO, dbo.CUDAN.GIOITINH, 
								 dbo.CUDAN.CHUNGMINHNHANDAN AS CMND_CUDAN
		FROM            dbo.CANHO INNER JOIN
								 dbo.[CUDAN-CANHO] ON dbo.CANHO.MACANHO = dbo.[CUDAN-CANHO].MACANHO INNER JOIN
								 dbo.CUDAN ON dbo.[CUDAN-CANHO].MACUDAN = dbo.CUDAN.MACUDAN INNER JOIN
								 dbo.LOAICANHO ON dbo.CANHO.MALOAI_CH = dbo.LOAICANHO.MALOAI_CH INNER JOIN
								 dbo.TANGLAU ON dbo.CANHO.MATANGLAU = dbo.TANGLAU.MATANGLAU INNER JOIN
								 dbo.TOANHA ON dbo.TANGLAU.MABLOCK = dbo.TOANHA.MABLOCK
	   WHERE dbo.[CUDAN-CANHO].NGAYHETO is null				 
 
	)  
SELECT c.*,cd.TENCUDAN AS TENCHUHO , cd.CHUNGMINHNHANDAN  as CMND_CHUHO
FROM DSCuDan  c
LEFT JOIN CUDAN cd on c.CHUHO = cd.MACUDAN
GO

/****** Object:  StoredProcedure [dbo].[PR_InserResident]    Script Date: 26-Jun-20 4:43:55 PM ******/
CREATE PROCEDURE [dbo].[PR_INSERT_CUDAN]
 @TenCuDan nvarchar(50),@NgaySinh date,@SoDienThoai varchar(10),@Cmnd varchar(10) , @GioiTinh int
AS
BEGIN	
	INSERT [dbo].[CUDAN] ([TENCUDAN], [NGAYSINH], [SODIENTHOAI], [CHUNGMINHNHANDAN] , [GIOITINH]) VALUES (@TenCuDan, @NgaySinh, @SoDienThoai, @Cmnd ,@GioiTinh)	
END
GO

CREATE PROCEDURE [dbo].[PR_UPDATE_CUDAN]
 @MaCuDan int, @TenCuDan nvarchar(50), @NgaySinh date, @SoDienThoai varchar(10), @Cmnd varchar(10) , @GioiTinh int
AS
BEGIN	
	UPDATE [dbo].[CUDAN] 
	SET [TENCUDAN] = @TenCuDan, [NGAYSINH] = @NgaySinh, [SODIENTHOAI] = @SoDienThoai , [CHUNGMINHNHANDAN] = @Cmnd, [GIOITINH] = @GioiTinh
	WHERE [MACUDAN] = @MaCuDan	
END
GO

CREATE PROC INSERT_APARTMENT 
	@MaCanHo varchar(10), @MaTangLau varchar(30),@MaLoaiCH varchar(30),@TenCanHo nvarchar(30),@SoNguoiO int, @ChuHo int
AS
BEGIN
	INSERT CANHO (MACANHO , MATANGLAU , MALOAI_CH , TENCANHO , SONGUOIO , CHUHO) 
	VALUE (@MaCanHo,@TenCanHo,@MaLoaiCH,@TenCanHo,@SoNguoiO, @ChuHo )
END
Go

CREATE PROC UPDATE_APARTMENT 
	@MaCanHo varchar(10), @MaTangLau varchar(30),@MaLoaiCH varchar(30),@TenCanHo nvarchar(30),@SoNguoiO int,@ChuHo int
AS
BEGIN
	UPDATE CANHO 
	SET MATANGLAU = @MaTangLau , MALOAI_CH = @MaLoaiCH , TENCANHO = @TenCanHo , SONGUOIO = @SoNguoiO , CHUHO = @ChuHo
	WHERE MACANHO = @MaCanHo
END
GO


create proc  PR_INSERT_CUDAN_CANHO 
	@MaCuDan int , @MaCanHo varchar(30) 
as
begin	
	INSERT [dbo].[CUDAN-CANHO] ([MACUDAN], [MACANHO], [NGAYBATDAUO], [NGAYHETO]) 
	VALUES (@MaCuDan, @MaCanHo, GetDate(), Null)	
end
go

create proc  PR_UPDATE_CUDAN_CANHO
	@Id int ,@MaCuDan int , @MaCanHo varchar(30) , @NgayVaoO date, @NgayHetO date
as
begin	
	UPDATE [dbo].[CUDAN-CANHO] 
	SET [NGAYBATDAUO] = @NgayVaoO, [NGAYHETO] =  @NgayHetO , MACUDAN	
	WHERE ID = @Id
end
go

-- Lấy thông tin chủ hộ từ căn hộ
create proc PR_LayThongTinChuHo 
	@maCanHo varchar(30)
AS
BEGIN
	SELECT * FROM CUDAN cd
	INNER JOIN CANHO ch ON cd.MACUDAN = ch.CHUHO
END
GO

create proc GetCustomApartment as
begin
	select tn.TENBLOCK,t.TENTANGLAU,ch.TENCANHO,lch.TENLOAI_CH,lch.DIENTICH,lch.SOPHONGNGU,lch.SONGUOITOIDA,ch.SONGUOIO,cd.TENCUDAN
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
end
go

create OR ALTER view VIEW_APARTMENT AS
	select ch.*,tn.MABLOCK, tn.TENBLOCK,t.TENTANGLAU,lch.TENLOAI_CH,cd.TENCUDAN as TENCHUho,cd.CHUNGMINHNHANDAN AS CMND_CHUHO
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
GO

create view VIEW_BLOCK AS
	select ch.*,tn.MABLOCK, tn.TENBLOCK,t.TENTANGLAU,lch.TENLOAI_CH,cd.MACUDAN,cd.CHUNGMINHNHANDAN 
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
GO


create view VIEW_FLOOR AS
	select tl.*,tn.TENBLOCK
	from TANGLAU tl
	inner join TOANHA tn on tn.MABLOCK = tl.MABLOCK
GO

create proc INSERT_FLOOR 
@MATANGLAU varchar(30), @TENTANGLAU nvarchar(50), @MABLOCK varchar(30)
as
begin
	INSERT TANGLAU (MATANGLAU,TENTANGLAU,MABLOCK) VALUES(@MATANGLAU,@TENTANGLAU,@MABLOCK)
end
go

create proc UPDATE_FLOOR 
@MATANGLAU varchar(30), @TENTANGLAU nvarchar(50), @MABLOCK varchar(30)
as
begin
	UPDATE TANGLAU 
	SET TENTANGLAU = @TENTANGLAU , MABLOCK = @MABLOCK
	WHERE MATANGLAU = @MATANGLAU
end
go

create proc PR_Insert_ApartmentCategogy
@MALOAI_CH VARCHAR(30) , @TENLOAI_CH NVARCHAR(50) , @DIENTICH INT , @SOPHONGNGU INT,@SONGUOITOIDA INT
AS
BEGIN
	INSERT LOAICANHO (MALOAI_CH,TENLOAI_CH,DIENTICH,SOPHONGNGU,SONGUOITOIDA)
	VALUES (@MALOAI_CH,@TENLOAI_CH,@DIENTICH,@SOPHONGNGU,@SONGUOITOIDA)
END
GO

create proc PR_Update_ApartmentCategogy
@MALOAI_CH VARCHAR(30) , @TENLOAI_CH NVARCHAR(50) , @DIENTICH INT , @SOPHONGNGU INT,@SONGUOITOIDA INT
AS
BEGIN
	UPDATE LOAICANHO 
	SET TENLOAI_CH = @TENLOAI_CH, DIENTICH = @DIENTICH,SOPHONGNGU = @SOPHONGNGU,SONGUOITOIDA = @SONGUOITOIDA
	WHERE MALOAI_CH = @MALOAI_CH
END
GO

--select * from LOAIDICHVU

create proc PR_Insert_ServiceCategogy 
 @TENLOAIDICHVU NVARCHAR(50), @NGUOITAO INT
AS
BEGIN
	INSERT LOAIDICHVU ( TENLOAIDICHVU , NGAYTAO , NGUOITAO , NGAYCAPNHAT , NGUOICAPNHAT )
	VALUES(@TENLOAIDICHVU , GETDATE(),@NGUOITAO,null,null)
END
GO

create proc PR_Update_ServiceCategogy 
@ID INT, @TENLOAIDICHVU NVARCHAR(50), @NGUOICAPNHAT INT
AS
BEGIN
	UPDATE LOAIDICHVU 
	SET TENLOAIDICHVU = @TENLOAIDICHVU ,  NGUOICAPNHAT = @NGUOICAPNHAT , NGAYCAPNHAT = GETDATE()
	WHERE ID = @ID
END
GO

Select * from DICHVU

create or alter view view_Service 
as
	select d.* , dv.TENLOAIDICHVU
	from DICHVU d
	inner join LOAIDICHVU dv on d.MALOAIDICHVU = dv.ID
go

create proc PR_Insert_Service
	@MALOAIDICHVU INT , @TENDICHVU NVARCHAR(50) , @DONVITINH INT , @NGUOITAO INT 
AS
BEGIN
	INSERT DICHVU (MALOAIDICHVU , TENDICHVU , DONVITINH , NGAYTAO , NGUOITAO)
	VALUES (@MALOAIDICHVU , @TENDICHVU ,@DONVITINH , GETDATE() , @NGUOITAO)
END
GO

create proc PR_Update_Service
@ID int, @MALOAIDICHVU INT , @TENDICHVU NVARCHAR(50) , @DONVITINH INT , @NGUOICAPNHAT INT
AS
BEGIN
	UPDATE DICHVU 
	SET MALOAIDICHVU = @MALOAIDICHVU , TENDICHVU = @TENDICHVU , DONVITINH = @DONVITINH , NGAYCAPNHAT = GETDATE() , NGUOICAPNHAT = @NGUOICAPNHAT
	WHERE ID = @ID
END
GO