
/****** Object:  StoredProcedure [dbo].[PR_login]    Script Date: 26-Jun-20 4:43:55 PM ******/
-- proc Login
CREATE PROCEDURE [dbo].[PR_login] 
 @username varchar(30), @password varchar(30)
AS
BEGIN
	SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @username and MATKHAU = @password
END

GO
-- Tao View Nhan Khau
CREATE VIEW VIEW_NHANKHAU AS 
	SELECT  cdch.* , ch.TENCANHO , cd.TENCUDAN , cd.NGAYSINH , cd.CHUNGMINHNHANDAN , cd.GIOITINH , cd.SODIENTHOAI
	FROM    dbo.[CUDAN-CANHO] cdch INNER JOIN
			dbo.[CANHO] ch ON cdch.MACANHO = ch.MACANHO INNER JOIN
			dbo.CUDAN cd ON cdch.MACUDAN =cd.MACUDAN 
 
GO
/****** Object:  StoredProcedure [dbo].[PR_InserResident]    Script Date: 26-Jun-20 4:43:55 PM ******/
CREATE PROCEDURE [dbo].[PR_INSERT_CUDAN]
 @TenCuDan nvarchar(50),@NgaySinh date,@SoDienThoai varchar(10),@Cmnd varchar(10) , @GioiTinh int
AS
BEGIN	
	INSERT [dbo].[CUDAN] ([TENCUDAN], [NGAYSINH], [SODIENTHOAI], [CHUNGMINHNHANDAN] , [GIOITINH]) VALUES (@TenCuDan, @NgaySinh, @SoDienThoai, @Cmnd ,@GioiTinh)	
END
GO

CREATE PROCEDURE [dbo].[PR_UPDATE_CUDAN]
 @MaCuDan int, @TenCuDan nvarchar(50), @NgaySinh date, @SoDienThoai varchar(10), @Cmnd varchar(10) , @GioiTinh int
AS
BEGIN	
	UPDATE [dbo].[CUDAN] 
	SET [TENCUDAN] = @TenCuDan, [NGAYSINH] = @NgaySinh, [SODIENTHOAI] = @SoDienThoai , [CHUNGMINHNHANDAN] = @Cmnd, [GIOITINH] = @GioiTinh
	WHERE [MACUDAN] = @MaCuDan	
END
GO

CREATE PROC INSERT_APARTMENT 
	@MaCanHo varchar(10), @MaTangLau varchar(30),@MaLoaiCH varchar(30),@TenCanHo nvarchar(30),@SoNguoiO int, @ChuHo int
AS
BEGIN
	INSERT CANHO (MACANHO , MATANGLAU , MALOAI_CH , TENCANHO , SONGUOIO , CHUHO) 
	VALUES (@MaCanHo,@TenCanHo,@MaLoaiCH,@TenCanHo,@SoNguoiO, @ChuHo )
END
Go

CREATE PROC UPDATE_APARTMENT 
	@MaCanHo varchar(10), @MaTangLau varchar(30),@MaLoaiCH varchar(30),@TenCanHo nvarchar(30),@SoNguoiO int,@ChuHo int
AS
BEGIN
	UPDATE CANHO 
	SET MATANGLAU = @MaTangLau , MALOAI_CH = @MaLoaiCH , TENCANHO = @TenCanHo , SONGUOIO = @SoNguoiO , CHUHO = @ChuHo
	WHERE MACANHO = @MaCanHo
END
GO


create proc  PR_INSERT_CUDAN_CANHO 
	@MaCuDan int , @MaCanHo varchar(30) 
as
begin	
	INSERT [dbo].[CUDAN-CANHO] ([MACUDAN], [MACANHO], [NGAYBATDAUO], [NGAYHETO]) 
	VALUES (@MaCuDan, @MaCanHo, GetDate(), Null)	
end
go

create proc  PR_UPDATE_CUDAN_CANHO
	@Id int ,@MaCuDan int , @MaCanHo varchar(30) , @NgayVaoO date, @NgayHetO date
as
begin	
	UPDATE [dbo].[CUDAN-CANHO] 
	SET [NGAYBATDAUO] = @NgayVaoO, [NGAYHETO] =  @NgayHetO , MACUDAN = @MaCuDan	
	WHERE ID = @Id
end
go

-- Lấy thông tin chủ hộ từ căn hộ
create proc PR_LayThongTinChuHo 
	@maCanHo varchar(30)
AS
BEGIN
	SELECT * FROM CUDAN cd
	INNER JOIN CANHO ch ON cd.MACUDAN = ch.CHUHO
END
GO

create proc PR_GetCustomApartment as
begin
	select tn.TENBLOCK,t.TENTANGLAU,ch.TENCANHO,lch.TENLOAI_CH,lch.DIENTICH,lch.SOPHONGNGU,lch.SONGUOITOIDA,ch.SONGUOIO,cd.TENCUDAN
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
end
go

create view VIEW_APARTMENT AS
	select ch.*,tn.MABLOCK, tn.TENBLOCK,t.TENTANGLAU,lch.TENLOAI_CH,cd.TENCUDAN as TENCHUho,cd.CHUNGMINHNHANDAN AS CMND_CHUHO
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
GO

create view VIEW_BLOCK AS
	select ch.*,tn.MABLOCK, tn.TENBLOCK,t.TENTANGLAU,lch.TENLOAI_CH,cd.MACUDAN,cd.CHUNGMINHNHANDAN 
	from CANHO ch
	inner join LOAICANHO lch on ch.MALOAI_CH = lch.MALOAI_CH
	inner join TANGLAU t on t.MATANGLAU = ch.MATANGLAU
	inner join TOANHA tn on tn.MABLOCK = t.MABLOCK
	left join CUDAN cd on ch.CHUHO = cd.MACUDAN
GO


create view VIEW_FLOOR AS
	select tl.*,tn.TENBLOCK
	from TANGLAU tl
	inner join TOANHA tn on tn.MABLOCK = tl.MABLOCK
GO

create proc PC_INSERT_FLOOR 
@MATANGLAU varchar(30), @TENTANGLAU nvarchar(50), @MABLOCK varchar(30)
as
begin
	INSERT TANGLAU (MATANGLAU,TENTANGLAU,MABLOCK) VALUES(@MATANGLAU,@TENTANGLAU,@MABLOCK)
end
go

create proc PR_UPDATE_FLOOR 
@MATANGLAU varchar(30), @TENTANGLAU nvarchar(50), @MABLOCK varchar(30)
as
begin
	UPDATE TANGLAU 
	SET TENTANGLAU = @TENTANGLAU , MABLOCK = @MABLOCK
	WHERE MATANGLAU = @MATANGLAU
end
go

create proc PR_Insert_ApartmentCategogy
@MALOAI_CH VARCHAR(30) , @TENLOAI_CH NVARCHAR(50) , @DIENTICH INT , @SOPHONGNGU INT,@SONGUOITOIDA INT
AS
BEGIN
	INSERT LOAICANHO (MALOAI_CH,TENLOAI_CH,DIENTICH,SOPHONGNGU,SONGUOITOIDA)
	VALUES (@MALOAI_CH,@TENLOAI_CH,@DIENTICH,@SOPHONGNGU,@SONGUOITOIDA)
END
GO

create proc PR_Update_ApartmentCategogy
@MALOAI_CH VARCHAR(30) , @TENLOAI_CH NVARCHAR(50) , @DIENTICH INT , @SOPHONGNGU INT,@SONGUOITOIDA INT
AS
BEGIN
	UPDATE LOAICANHO 
	SET TENLOAI_CH = @TENLOAI_CH, DIENTICH = @DIENTICH,SOPHONGNGU = @SOPHONGNGU,SONGUOITOIDA = @SONGUOITOIDA
	WHERE MALOAI_CH = @MALOAI_CH
END
GO

--select * from LOAIDICHVU

create proc PR_Insert_ServiceCategogy 
 @TENLOAIDICHVU NVARCHAR(50), @CREATE_BY INT
AS
BEGIN
	INSERT LOAIDICHVU ( TENLOAIDICHVU , CREATE_DATE , CREATE_BY , UPDATE_DATE , UPDATE_BY )
	VALUES(@TENLOAIDICHVU , GETDATE(),@CREATE_BY,null,null)
END
GO

create proc PR_Update_ServiceCategogy 
@ID INT, @TENLOAIDICHVU NVARCHAR(50), @UPDATE_BY INT
AS
BEGIN
	UPDATE LOAIDICHVU 
	SET TENLOAIDICHVU = @TENLOAIDICHVU ,  UPDATE_BY = @UPDATE_BY , UPDATE_DATE = GETDATE()
	WHERE ID = @ID
END
GO

create view VIEW_SERVICE 
as
	select d.* , dv.TENLOAIDICHVU
	from DICHVU d
	inner join LOAIDICHVU dv on d.MALOAIDICHVU = dv.ID
go

create proc PR_Insert_Service
	@MALOAIDICHVU INT , @TENDICHVU NVARCHAR(50) , @DONVITINH INT , @CREATE_BY INT 
AS
	INSERT DICHVU (MALOAIDICHVU , TENDICHVU , DONVITINH , CREATE_DATE , CREATE_BY)
	VALUES (@MALOAIDICHVU , @TENDICHVU ,@DONVITINH , GETDATE() , @CREATE_BY)
END
GO

create proc PR_Update_Service
@ID int, @MALOAIDICHVU INT , @TENDICHVU NVARCHAR(50) , @DONVITINH INT , @UPDATE_BY INT
AS
BEGIN
	UPDATE DICHVU 
	SET MALOAIDICHVU = @MALOAIDICHVU , TENDICHVU = @TENDICHVU , DONVITINH = @DONVITINH , UPDATE_DATE = GETDATE() , UPDATE_BY = @UPDATE_BY
	WHERE ID = @ID
GO

CREATE PROC PR_CHANGR_HOME
	@OLD_HOME VARCHAR(30) , @NEW_HOME VARCHAR(30)
AS
BEGIN
	UPDATE CANHO SET SONGUOIO = SONGUOIO - 1 WHERE MACANHO = @OLD_HOME 
	UPDATE CANHO SET SONGUOIO = SONGUOIO + 1 WHERE MACANHO = @NEW_HOME 
END
GO